esphome:
  name: esp-yamaha
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

remote_transmitter:
  - id: ir_out
    pin: 
      number: D2
      inverted: False
    carrier_duty_percent: 50%
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Yamaha Fallback Hotspot"
    password: !secret wifi_password
    
# Enable Home Assistant API
api:
  services:
    - service: remote_2code
      variables:
        rc_code_1: int
        rc_code_2: int
      then:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: !lambda 'return rc_code_1;'
          rc_code_2: !lambda 'return rc_code_2;'
          repeat:
            times: 2
    - service: remote_1code
      variables:
        rc_code_1: int
      then:
      - remote_transmitter.transmit_pioneer:
          rc_code_1: !lambda 'return rc_code_1;'
          repeat:
            times: 2

    - service: power_on
      then:
        - remote_transmitter.transmit_pioneer:
            # YAMAHA ON
            rc_code_1: 0x7E7E

    - service: power_off
      then:
        - remote_transmitter.transmit_pioneer:
            # YAMAHA OFF
            rc_code_1: 0x7E7F

    - service: volume_up
      then:
        - remote_transmitter.transmit_pioneer:
            # YAMAHA VOLUME UP
            rc_code_1: 0x5E1A

    - service: volume_down
      then:
        - remote_transmitter.transmit_pioneer:
            # YAMAHA VOLUME DOWN
            rc_code_1: 0x5E1B
            
    - service: select_tv
      then:
        - remote_transmitter.transmit_pioneer:
            # YAMAHA DTV/CABLE
            rc_code_1: 0x5E54

    - service: select_volumio
      then:
        - remote_transmitter.transmit_pioneer:
            # YAMAHA MD/CDR
            rc_code_1: 0x5EC9
            
    - service: select_mibox
      then:
        - remote_transmitter.transmit_pioneer:
            # YAMAHA DVR
            rc_code_1: 0x5E13            

captive_portal:
